const { resolve } = require('path');

module.exports = {
  publicDir: 'assets',
  plugins: [],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        foundations: resolve(__dirname, 'foundations.html'),
        startHere: resolve(__dirname, 'start-here.html'),
        catechism: resolve(__dirname, 'catechism.html'),
        catechismGod: resolve(__dirname, 'catechism-god.html'),
        catechismCreation: resolve(__dirname, 'catechism-creation.html'),
        catechismHumanVocation: resolve(__dirname, 'catechism-human-vocation.html'),
        catechismGraceFreedom: resolve(__dirname, 'catechism-grace-freedom.html'),
        catechismDeathHope: resolve(__dirname, 'catechism-death-hope.html'),
        divineLaw: resolve(__dirname, 'divine-law.html'),
        divineLawExtended: resolve(__dirname, 'divine-law-extended.html'),
        chaosOrder: resolve(__dirname, 'chaos-order.html'),
        fateDestiny: resolve(__dirname, 'fate-destiny.html'),
        heavenHellJourney: resolve(__dirname, 'heaven-hell-journey.html'),
        namesOfGod: resolve(__dirname, 'names-of-god.html'),
        textsLibrary: resolve(__dirname, 'texts-library.html'),
        inquiryForum: resolve(__dirname, 'inquiry-forum.html'),
        practice: resolve(__dirname, 'practice.html'),
        sermons: resolve(__dirname, 'sermons.html'),
        glossary: resolve(__dirname, 'glossary.html'),
        condemnation: resolve(__dirname, 'condemnation.html'),
        condemnation2: resolve(__dirname, 'condemnation-2.html'),
        condemnation3: resolve(__dirname, 'condemnation-3.html'),
        about: resolve(__dirname, 'about.html'),
        forum: resolve(__dirname, 'forum.html'),
        forumWelcome: resolve(__dirname, 'forum/welcome.html'),
        forumGuidelines: resolve(__dirname, 'forum/guidelines.html'),
        forumFAQ: resolve(__dirname, 'forum/faq.html'),
        forumHelp: resolve(__dirname, 'forum/help.html'),
        forumIntroductions: resolve(__dirname, 'forum/introductions.html'),
        forumAnnouncements: resolve(__dirname, 'forum/announcements.html'),
        forumLifeDeath: resolve(__dirname, 'forum/life-and-death-questions.html'),
        forumPrayerReflections: resolve(__dirname, 'forum/prayer-and-reflections.html'),
        forumFeed: resolve(__dirname, 'forum-feed.html'),
        forumNew: resolve(__dirname, 'forum/new.html'),
        forumPost: resolve(__dirname, 'forum/post.html'),
        moderation: resolve(__dirname, 'moderation.html'),
        philosophy: resolve(__dirname, 'philosophy.html'),
        philosophy2: resolve(__dirname, 'philosophy-2.html'),
        essayTen: resolve(__dirname, 'essays/ten-commandments.html'),
        essayProvFree: resolve(__dirname, 'essays/providence-and-freedom.html'),
        guideExamen: resolve(__dirname, 'guides/examen.html'),
        guideLectio: resolve(__dirname, 'guides/lectio-divina.html'),
        guideRule: resolve(__dirname, 'guides/rule-of-life.html'),
      },
    },
  },
};

